---
- name: configure SOE
  hosts: serverb
  remote_user: student
  become: true
  vars:
    - system_owner: Mr. SHIVKANSH SINGH 

  tasks:
    - name: coonfigure /etc/motd
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
