---
- name: new play for httpd
  hosts: servera
  tasks:
    - name: install httpd & firewalld
      ansible.builtin.dnf:
        name:
          - httpd
          - firewalld
        state: absent
    - name: add new contant in httpd
      ansible.builtin.copy:
        content: "Welcome to redhat\n"
        dest: /var/www/html/index.html
    - name: start firewalld service
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started
    - name: add http in firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
    - name: start httpd service
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

