---
- name: Task Failure Exercise
  hosts: servera
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: Attempt to set up a webserver
      block:
        - name: Install {{ web_package }} package
          dnf:
            name: "{{ web_package }}"
            state: present

      rescue:
        - name: Install {{ db_package }} package
          dnf:
            name: "{{ db_package }}"
            state: present

      always:
        - name: Start {{ db_service }} service
          service:
            name: "{{ db_service }}"
            state: started
